name: Test and Lint

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - '**'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. Lint 검사
      - name: Run Lint
        run: npm run lint

      # 5. Jest 테스트 실행 및 커버리지 리포트 생성
      - name: Run Jest Tests with Coverage
        run: npm run test -- --coverage

      # 6. 코드 커버리지 리포트를 GitHub Actions에 표시
      - name: Upload Coverage to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-${{ matrix.node-version }}
          path: coverage/

      # 7. 성공 시 PR에 코멘트 추가
      - name: Add Success Comment for Build and Test
        if: success()
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✅ **테스트 파일 실행** 작업이 성공적으로 완료되었습니다!
            - Node.js 버전: ${{ matrix.node-version }}

      # 8. 실패 시 PR에 코멘트 추가
      - name: Add Failure Comment for Build and Test
        if: failure()
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ❌ **테스트 파일 실행** 작업이 실패했습니다.
            - Node.js 버전: ${{ matrix.node-version }}
            - 오류 내용을 확인해주세요.

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. Lint 검사
      - name: Run Lint
        run: npm run lint

      # 5. 성공 시 PR에 코멘트 추가
      - name: Add Success Comment for Lint
        if: success()
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✅ **Lint 확인** 작업이 성공적으로 완료되었습니다!
            - Node.js 버전: ${{ matrix.node-version }}

      # 6. 실패 시 PR에 코멘트 추가
      - name: Add Failure Comment for Lint
        if: failure()
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ❌ **Lint 확인** 작업이 실패했습니다.
            - Node.js 버전: ${{ matrix.node-version }}
            - 오류 내용을 확인해주세요.
